### ISSUE TITLE
bump version

### ISSUE THREAD

**Issue by justinclayton** [Capgemini/dcos-cli-docker#3]
This is awesome. My only issue was that there wasn't the newest version installed in your container, so I had to build from your Dockerfile again and push my own copy. I suspect #2 should resolve this as well, but if you happen to have time to bump the version, that would be fantastic.

**Comment by tayzlor** [comment]
Closing via https://github.com/Capgemini/dcos-cli-docker/pull/4

**Comment by justinclayton** [comment]
Fantastic, thanks!
